name: norseenv
channels:
  - conda-forge
  - pytorch
dependencies:
  # Dependencies
  - torch
  - python
  - pip

  # Build
  - cmake
  - ninja
  - pybind11

  # Python
  - black
  - pytest
  - pytype