name: C++ package

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-cpp:
    runs-on: ${{ matrix.config.os }}
    strategy:
      max-parallel: 4
      matrix:
        config:
          - { name: "Windows cl", os: windows-latest, cc: "cl", cxx: "cl" }
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
          - {
              name: "MacOS clang",
              os: macos-latest,
              cc: "clang",
              cxx: "clang++",
            }
        python-version: [3.7, 3.8, 3.9]
    name: "Build C++ - ${{ matrix.config.name}} Python v${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        if: ${{ !env.ACT }} # Cache not working due to https://github.com/nektos/act/issues/329
        uses: actions/cache@master
        env:
          # Increase this value to reset cache if environment.yaml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/cpp_pkgs_dir
          key: ${{ runner.os }}-python${{ matrix.python-version }}-${{ env.CACHE_NUMBER }} }}
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: "3.20.x"
      - name: (Ubuntu) Install G++ and libtorch
        if: ${{ matrix.config.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install g++ libgtest-dev ninja-build -y
          wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.9.0%2Bcpu.zip -O ${{ github.workspace }}/libtorch.zip
          unzip -q ${{ github.workspace }}/libtorch.zip -d ${{ github.workspace }}/
      - name: (MacOS) Install clang and libtorch
        if: ${{ matrix.config.os == 'macos-latest' }}
        run: |
          brew install llvm ninja
          wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.9.0%2Bcpu.zip -O ${{ github.workspace }}/libtorch.zip
          unzip -q ${{ github.workspace }}/libtorch.zip -d ${{ github.workspace }}/
      - name: (Windows) Install Chocolatey
        if: ${{ matrix.config.os == 'windows-latest' }}
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install python cmake ninja wget unzip
      - name: (Windows) Install libtorch
        if: ${{ matrix.config.os == 'windows-latest'}}
        run: |
          wget https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.9.0%2Bcpu.zip -O ${{ github.workspace }}/libtorch.zip
          unzip -q ${{ github.workspace }}/libtorch.zip -d ${{ github.workspace }}/
      - run: cd ${{ github.workspace }} && pwd && ls
      - run: env
      - name: Build
        run: |
          cmake -GNinja -B build -S . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_PREFIX_PATH=${{ github.workspace }}/libtorch
          cmake --build build
      - name: Test
        run: |
          ctest --test-dir build/norse/csrc
