name: Publish to Conda

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo "name=RELEASE_VERSION" >> $GITHUB_ENV
    - name: publish-to-conda
      uses: jegp/conda-package-publish-action@v1.2
      with:
        subDir: 'publish/conda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}