name: Python package

on: [push, pull_request]

jobs:
  build-python:
    runs-on: ubuntu-latest #${{ matrix.config.os }}
    strategy:
      max-parallel: 4
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest }
          - { name: "Ubuntu gcc", os: ubuntu-latest }
          - { name: "MacOS clang", os: macos-latest }
        python-version: [3.7, 3.8, 3.9]

    name: "Build: ${{ matrix.config.os}} Python v${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        if: ${{ !env.ACT }}
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yaml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/python_pkgs_dir
          key: ${{ runner.os }}-python-${{ env.CACHE_NUMBER }}-${{hashFiles('${{ matrix.config.conda }}') }}
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: pytest norse --cov=norse/torch --cov-config=.coveragerc --cov-report=xml
      - name: Type check
        run: pytype norse
      - name: Lint
        run: black --check norse
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
